
name: ci

on:
  push:
    tags:
      - v*
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: set up
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
        id: go

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.11.3

      - name: test
        run: go test ./... -v

      - name: build
        run: go build -v cmd/main.go
